version: "3"

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  nats:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  redis:
    image: redis
    ports:
      - 6379:6379
